### ISSUE TITLE
Unable to build 5.16.2

### ISSUE THREAD

**Issue by Lakshmi5785-dev** [OpenC3/cosmos#1319]
First check out our main documentation site at [https://openc3.com](https://openc3.com).

Its on Windows 11
Next search the issues here on Github. If you come up empty please submit an issue.
<img width="845" alt="image" src="https://github.com/OpenC3/cosmos/assets/54974578/e546b945-4dca-46b8-970f-2c87cbf169a2">

**Comment by jmthomas** [comment]
It obviously builds for us and it's hard for me to think this is a Windows issue since we're pulling in node packages. I couldn't come up with anything obvious during a search either. I see the error is on buildLocale ... weird question but are you building on an English locale computer? Also is this a new error on a new machine ... I assume you've been able to build in the past?

**Comment by Lakshmi5785-dev** [comment]
Hi Thomas,
      Yes I have build all the previous verstion and they are running fine on my machine(atleast upto 5.15 I have tried). I have trouble only with this build. And also I tried on 2 machines with same configuration and both of them got stuck with the same error. Its a local windows machine.

**Comment by jmthomas** [comment]
@Lakshmi5785-dev Does this still occur on 5.16? 5.17? Are you in a batch shell or powershell? Is this OBE?

**Comment by Lakshmi5785-dev** [comment]
I didn't try on 5.17 Thomos, Will give a try and inform you here this week.

**Comment by jmthomas** [comment]
I think this is OBE
