### ISSUE TITLE
REST API loading gem files

### ISSUE THREAD

**Issue by rashuky** [OpenC3/cosmos#158]
Is there a way to programmatically upload gem files using REST API? 

I went through the documentation on https://openc3.com/docs/v5/ and couldn't find any information about it. I found only JSON and streaming API, but I don't think that I could use any of those for this purpose.

**Comment by ryanmelt** [comment]
Yes it is possible to do this using our APIs.   

APIs outside of the scripting API aren't well documented yet, largely because the client-side code is only implemented in Javascript and used by our frontend.   The easiest way to see how they are used is the fronted code itself.   

For installing plugins, the Admin plugin tab code would be the place to start:

https://github.com/OpenC3/openc3/blob/master/openc3-init/plugins/packages/openc3-tool-common/src/tools/admin/tabs/PluginsTab.vue

Installing a plugin is a two step process and not super trivial to implement.

**Comment by GTI-Dakota** [comment]
Is there a way to do this in the current version? The link provided goes nowhere

**Comment by ryanmelt** [comment]
We just end the Ruby client code to do this in 5.6.0.   The Enterprise release should be ready  in a couple hours

**Comment by GTI-Dakota** [comment]
Where should I reference to get started on rest API loading?

**Comment by ryanmelt** [comment]
The Ruby client code is here:
https://github.com/OpenC3/cosmos/blob/main/openc3/lib/openc3/script/plugins.rb

**Comment by GTI-Dakota** [comment]
Awesome, thanks

**Comment by tsjordan-eng** [comment]
I started working on a rake target to upgrade my plugins. So `rake update` or something would build, upload, and upgrade the new gem. Is that something you'd be interested in? Did you make any progress on this?

**Comment by ryanmelt** [comment]
```openc3cli load gemname.gem``` should work now if it has all the right environment variables set.

**Comment by rmslick** [comment]
Sorry to resurrect this thread, but what environment variables need to be set? When I run the above I get an error: Unable to resolv api hostname: openc3-cosmos-cmd-tlm-api. Thanks
