### ISSUE TITLE
Time Travelling Python Debugging

### ISSUE THREAD

**Issue by stephen-ritter** [OpenC3/cosmos#1707]
There is a need to be able to rewind a script if it gets stuck or to jump to a specific line. It appears there isn't great support for this in either Python or Ruby. In Python it appears some people have tried to tackle this issue. One of the latest ones I have seen is called pytrace, and it also has integration with a web frontend. Overall I was wondering if something like this debugger could be implemented in the Script Runner.
https://pytrace.com/
https://github.com/gleb-sevruk/pycrunch-trace

**Comment by jmthomas** [comment]
We currently have an open ticket for executing selected lines while paused: https://github.com/OpenC3/cosmos/pull/1638. It needs some backend work which is why it's not closed.

It looks like pytrace and pycrunch-trace both have their own frontends for viewing trace files. It almost looks more like a profiler like [ruby-prof](https://ruby-prof.github.io/). Whatever we do will be implemented within Script Runner itself.

Right now the debugger works pretty good for inspecting and setting variables but you're limited to executing step by step forward with no other traversal options.
