### ISSUE TITLE
Issue with the WIDTH setting in telemetry screens

### ISSUE THREAD

**Issue by bradenvirdellgenevatech** [OpenC3/cosmos#310]
First check out our main documentation site at [https://openc3.com](https://openc3.com).

**Describe the bug**
The width setting for Screens appears to broken and not properly setting the width for widgets. This is after upgrading from 5.0.11 to 5.1.1. I noticed you had an issue out for the width setting in 5.1.0 not sure if that is what is causing the issue. 

**To Reproduce**
Add value or labelvaluedesc and set its width 

**Expected behavior**
The Width to be the specific number of pixels I am stating. In the example in the screen shots I would expect the value and the Button to be the same width but they clearly are not

**Screenshots**
The first screen shot is of what I am using to create the screen. 
![width issue](https://user-images.githubusercontent.com/111302076/205761923-cd780c99-ed4b-496e-adbe-37f958bbab55.png)
The second is the screen it produces.
![image](https://user-images.githubusercontent.com/111302076/205762414-064c5e31-d81e-4955-8a1a-0224dafd20cf.png)

**Environment (please complete the following information):**
Windows
Chrome
OpenC3 COSMOS Version 5.1.1

**Comment by jmthomas** [comment]
When using the SETTING values you need to provide the css units. For example in our demo:

```
SCREEN AUTO AUTO 1.0
LABELVALUEDESC INST HEALTH_STATUS COLLECTS
VALUE INST HEALTH_STATUS COLLECTS
  SETTING WIDTH 200px
BUTTON "HELLO THERE"
  SETTING WIDTH 200px
```

Results in:
![Screenshot 2022-12-07 at 8 31 39 AM](https://user-images.githubusercontent.com/176403/206221545-47887e23-e1ff-4d57-ba8b-0540de9f6aa9.png)

Note there are slight differences due to padding and the widget types in Vuetify.js. You can try other [css units](https://www.w3schools.com/cssref/css_units.php) to get various results.

When using our widgets directly, some have a width field in the settings. For example [TEXTFIELD](https://openc3.com/docs/v5/screens#textfield) takes the width of the field in characters. We implement this using the 'ch' units in CSS but that's something we apply automatically for you.

I will update the documentation.
