### ISSUE TITLE
Option for Packet Viewer to show all rows by default

### ISSUE THREAD

**Issue by scandey** [OpenC3/cosmos#360]
**Is your feature request related to a problem? Please describe.**
Even with long packets, I always want to see every row in Packet Viewer. I have to constantly remember to find the "Rows per Page" option in the bottom right and set it to "all". 

**Describe the solution you'd like**
I'd like an option to always display all rows, even though it may be much slower to load the page. 

**Additional context**
In CmdTlmServer, rows per page are limited to max 100, and I sometimes (though rarely) wish I could do the same thing where I just see all of the 100s of telemetry and command packets defined. The search option is much more effective here though, since packet titles tend to be named much better than internal packet mnemonics.

**Comment by jmthomas** [comment]
I think we could keep a setting in the local storage which indicates your preference for the total number of rows to display. This could potentially carry over to CmdTlmServer as well but the answer will probably never be "All". If you have thousands of items defined in a packet it just takes too long to query everything and return them all at a 1Hz refresh rate and we don't want to simply "break" PacketViewer. I think a default value of 20 (rather than 10) and a max of maybe 1000 (would have to test) would be more reasonable.
