### ISSUE TITLE
Script Debug Step mode usage

### ISSUE THREAD

**Issue by MTI-twalker** [OpenC3/cosmos#405]
In the documentation, the functions under "Debugging" are all marked as unimplemented in the table:
[Debugging](https://openc3.com/docs/v5/scripting#debugging)
(Except for insert_return is not mentioned but is also not implemented)

Will step mode be implemented? 
Can suite runner include a "step mode" optional checkbox?

I am not sure if they are the same thing but, when I go to Script Runner:
 - Select "SCRIPT" at the top
 - Select "Toggle Debug"

A line appears above the output log. The step button results in a 404 error. I am not totally sure what the debug line does. Is that button meant for stepping through line by line?

As a workaround I setup an environment variable called run_mode and I added the lines:
wait() unless run_mode == 'true'

Then I set the environment variable to either true or not true to get the step through that I wanted. I assume this is essentially what would be going on in step_mode except in the background. I am hoping to not have to include that under each line.

**Comment by jmthomas** [comment]
The Toggle Debug with Step button is how you step through scripts. It does not START the script but only steps through after a script has been paused. I can see how this is a little confusing. I would be ok with the Step button START a script and immediately putting it into step mode. However, I'm not sure how that would work in Suite mode because you can start either a Suite, Group, or Script. Bottom line is that it should be greyed out unless you can use it.
