### ISSUE TITLE
Informational logging control

### ISSUE THREAD

**Issue by sambarusty** [OpenC3/cosmos#864]
I was wondering if there is a setting somewhere that would allow us to turn off the informational stuff that is being printed out within the CMD_TLM_API.  I was investigating a performance issue when creating a screen to show many fields and noticed if I do a podman logs on the cmd-tlm-api container, it looks like every time it goes to update the display calling get_tlm_values, it has an informational log that prints out every field it is updating the display with.  I was wondering if I could turn that off to see if it would improve performance.

**Comment by jmthomas** [comment]
Unfortunately there is no way to disable this logging. The `get_tlm_values` in particular is a very heavy API item as it is called for all the screens. We will consider filtering or otherwise disable this logging going foward.

Note that we made significant improvements to the screen APIs in [5.9.1](https://github.com/OpenC3/cosmos/releases/tag/v5.9.1) so if you're before that release please upgrade!
